export const links = [
  {
    name: "Home",
    url: "/",
  },
  {
    name: "About",
    url: "/about",
  },
  {
    name: "Services",
    url: "/services",
  },
  {
    name: "Rates",
    url: "/rates",
  },
  {
    name: "My Page",
    url: "/mypage",
  },
] as const;

export const currencies = [
  {
    symbol: "AUD",
    name: "Australian Dollar",
    flag: "🇦🇺",
    display: "🇦🇺\xa0\xa0\xa0\xa0\xa0\xa0AUD-Australian Dollar",
  },
  {
    symbol: "BGN",
    name: "Bulgarian Lev",
    flag: "🇧🇬",
    display: "🇧🇬\xa0\xa0\xa0\xa0\xa0\xa0BGN-Bulgarian Lev",
  },
  {
    symbol: "BRL",
    name: "Brazilian Real",
    flag: "🇧🇷",
    display: "🇧🇷\xa0\xa0\xa0\xa0\xa0\xa0BRL-Brazilian Real",
  },
  {
    symbol: "CAD",
    name: "Canadian Dollar",
    flag: "🇨🇦",
    display: "🇨🇦\xa0\xa0\xa0\xa0\xa0\xa0CAD-Canadian Dollar",
  },
  {
    symbol: "CHF",
    name: "Swiss Franc",
    flag: "🇨🇭",
    display: "🇨🇭\xa0\xa0\xa0\xa0\xa0\xa0CHF-Swiss Franc",
  },
  {
    symbol: "CNY",
    name: "Chinese Renminbi Yuan",
    flag: "🇨🇳",
    display: "🇨🇳\xa0\xa0\xa0\xa0\xa0\xa0CNY-Chinese Renminbi Yuan",
  },
  {
    symbol: "CZK",
    name: "Czech Koruna",
    flag: "🇨🇿",
    display: "🇨🇿\xa0\xa0\xa0\xa0\xa0\xa0CZK-Czech Koruna",
  },
  {
    symbol: "DKK",
    name: "Danish Krone",
    flag: "🇩🇰",
    display: "🇩🇰\xa0\xa0\xa0\xa0\xa0\xa0DKK-Danish Krone",
  },
  {
    symbol: "EUR",
    name: "Euro",
    flag: "🇪🇺",
    display: "🇪🇺\xa0\xa0\xa0\xa0\xa0\xa0EUR-Euro",
  },
  {
    symbol: "GBP",
    name: "British Pound",
    flag: "🇬🇧",
    display: "🇬🇧\xa0\xa0\xa0\xa0\xa0\xa0GBP-British Pound",
  },
  {
    symbol: "HKD",
    name: "Hong Kong Dollar",
    flag: "🇭🇰",
    display: "🇭🇰\xa0\xa0\xa0\xa0\xa0\xa0HKD-Hong Kong Dollar",
  },
  {
    symbol: "HUF",
    name: "Hungarian Forint",
    flag: "🇭🇺",
    display: "🇭🇺\xa0\xa0\xa0\xa0\xa0\xa0HUF-Hungarian Forint",
  },
  {
    symbol: "IDR",
    name: "Indonesian Rupiah",
    flag: "🇮🇩",
    display: "🇮🇩\xa0\xa0\xa0\xa0\xa0\xa0IDR-Indonesian Rupiah",
  },
  {
    symbol: "INR",
    name: "Indian Rupee",
    flag: "🇮🇳",
    display: "🇮🇳\xa0\xa0\xa0\xa0\xa0\xa0INR-Indian Rupee",
  },
  {
    symbol: "ISK",
    name: "Icelandic Króna",
    flag: "🇮🇸",
    display: "🇮🇸\xa0\xa0\xa0\xa0\xa0\xa0ISK-Icelandic Króna",
  },
  {
    symbol: "JPY",
    name: "Japanese Yen",
    flag: "🇯🇵",
    display: "🇯🇵\xa0\xa0\xa0\xa0\xa0\xa0JPY-Japanese Yen",
  },
  {
    symbol: "KRW",
    name: "South Korean Won",
    flag: "🇰🇷",
    display: "🇰🇷\xa0\xa0\xa0\xa0\xa0\xa0KRW-South Korean Won",
  },
  {
    symbol: "MXN",
    name: "Mexican Peso",
    flag: "🇲🇽",
    display: "🇲🇽\xa0\xa0\xa0\xa0\xa0\xa0MXN-Mexican Peso",
  },
  {
    symbol: "MYR",
    name: "Malaysian Ringgit",
    flag: "🇲🇾",
    display: "🇲🇾\xa0\xa0\xa0\xa0\xa0\xa0MYR-Malaysian Ringgit",
  },
  {
    symbol: "NOK",
    name: "Norwegian Krone",
    flag: "🇳🇴",
    display: "🇳🇴\xa0\xa0\xa0\xa0\xa0\xa0NOK-Norwegian Krone",
  },
  {
    symbol: "NZD",
    name: "New Zealand Dollar",
    flag: "🇳🇿",
    display: "🇳🇿\xa0\xa0\xa0\xa0\xa0\xa0NZD-New Zealand Dollar",
  },
  {
    symbol: "PHP",
    name: "Philippine Peso",
    flag: "🇵🇭",
    display: "🇵🇭\xa0\xa0\xa0\xa0\xa0\xa0PHP-Philippine Peso",
  },
  {
    symbol: "PLN",
    name: "Polish złoty",
    flag: "🇵🇱",
    display: "🇵🇱\xa0\xa0\xa0\xa0\xa0\xa0PLN-Polish złoty",
  },
  {
    symbol: "RON",
    name: "Romanian Leu",
    flag: "🇷🇴",
    display: "🇷🇴\xa0\xa0\xa0\xa0\xa0\xa0RON-Romanian Leu",
  },
  {
    symbol: "SEK",
    name: "Swedish Krona",
    flag: "🇸🇪",
    display: "🇸🇪\xa0\xa0\xa0\xa0\xa0\xa0SEK-Swedish Krona",
  },
  {
    symbol: "SGD",
    name: "Singapore Dollar",
    flag: "🇸🇬",
    display: "🇸🇬\xa0\xa0\xa0\xa0\xa0\xa0SGD-Singapore Dollar",
  },
  {
    symbol: "THB",
    name: "Thai Baht",
    flag: "🇹🇭",
    display: "🇹🇭\xa0\xa0\xa0\xa0\xa0\xa0THB-Thai Baht",
  },
  {
    symbol: "TRY",
    name: "Turkish Lira",
    flag: "🇹🇷",
    display: "🇹🇷\xa0\xa0\xa0\xa0\xa0\xa0TRY-Turkish Lira",
  },
  {
    symbol: "USD",
    name: "United States Dollar",
    flag: "🇺🇸",
    display: "🇺🇸\xa0\xa0\xa0\xa0\xa0\xa0USD-United States Dollar",
  },
  {
    symbol: "ZAR",
    name: "South African Rand",
    flag: "🇿🇦",
    display: "🇿🇦\xa0\xa0\xa0\xa0\xa0\xa0ZAR-South African Rand",
  },
] as const;
